### Day 11

In [1]:
import numpy as np
from collections import defaultdict, Counter

In [2]:
day_i = 11

In [3]:
%run start_day.py $day_i

Initializing day 11


In [4]:
cd /home/vincent/Documents/AdventOfCode/2021

/home/vincent/Documents/AdventOfCode/2021


In [5]:
PATH = f"day{day_i}/input{day_i}"

In [6]:
!wc -l $PATH

10 day11/input11


In [7]:
!head $PATH

8271653836
7567626775
2315713316
6542655315
2453637333
1247264328
2325146614
2115843171
6182376282
2384738675


In [ ]:
!tail $PATH

In [8]:
def parse_input(inp):
    return np.array([list(map(int, x)) for x in inp])

In [9]:
# real input
with open(PATH, 'r') as f:
    arr = parse_input([x.strip() for x in f.readlines()])

    print(arr.shape)

(10, 10)


In [10]:
print(arr)

[[8 2 7 1 6 5 3 8 3 6]
 [7 5 6 7 6 2 6 7 7 5]
 [2 3 1 5 7 1 3 3 1 6]
 [6 5 4 2 6 5 5 3 1 5]
 [2 4 5 3 6 3 7 3 3 3]
 [1 2 4 7 2 6 4 3 2 8]
 [2 3 2 5 1 4 6 6 1 4]
 [2 1 1 5 8 4 3 1 7 1]
 [6 1 8 2 3 7 6 2 8 2]
 [2 3 8 4 7 3 8 6 7 5]]


In [31]:
# test input
test_str = """5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

test_str2 = """11111
19991
19191
19991
11111"""

arr_test = parse_input(test_str.split('\n'))
arr_test2 = parse_input(test_str2.split('\n'))

In [15]:
from scipy.signal import convolve2d

In [48]:
KERNEL = np.array([[1, 1, 1],
                   [1, 0, 1],
                   [1, 1, 1]])

def one_step(arr_input):
    a = arr_input.copy()
    n, m = a.shape
    a += 1
    flashing = (a > 9).astype(int)
    flashed = np.zeros_like(flashing)
    while np.sum(flashing) > 0:
        to_add = convolve2d(flashing, KERNEL, mode='same')
        flashed += flashing
        a += to_add
        flashing = (1 - flashed) * (a > 9)
    a[flashed == 1] = 0
    return a, np.sum(flashed)

def solve1(arr_input, n_steps):
    total = 0
    a = arr_input.copy()
    for _ in range(n_steps):
        new_a, x = one_step(a)
        total += x
        a = new_a
    return total

def solve2(arr_input):
    n, m = arr_input.shape
    a = arr_input.copy()
    step = 0
    while True:
        step += 1
        new_a, x = one_step(a)
        if x == n*m:
            return step
        a = new_a

In [43]:
one_step(arr_test2)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

flashed
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


(array([[3, 4, 5, 4, 3],
        [4, 0, 0, 0, 4],
        [5, 0, 0, 0, 5],
        [4, 0, 0, 0, 4],
        [3, 4, 5, 4, 3]]),
 9)

In [45]:
solve1(arr_test, 10)

204

In [46]:
solve1(arr_test, 100)

1656

In [47]:
solve1(arr, 100)

1562

In [49]:
solve2(arr_test)

195

In [50]:
solve2(arr)

268