### Day 9

In [1]:
import numpy as np
from collections import defaultdict, Counter

In [2]:
day_i = 9

In [3]:
%run start_day.py $day_i

Initializing day 9


In [4]:
cd /home/vincent/Documents/AdventOfCode/2021

/home/vincent/Documents/AdventOfCode/2021


In [5]:
PATH = f"day{day_i}/input{day_i}"

In [6]:
!wc -l $PATH

100 day9/input9


In [7]:
!head $PATH

8765432876678945459896432459890123456789219865434989979901998765323556789657898764567891098998765434
9874321234589432348789321598799234678897909954329878567899899877612345678945999843456792987989896749
8763210345694321245697632987678949789956798768210965456789789998543456989656795432345679876578987898
9654321256789490126789549876567898991239899876361294389895678987654567899878985321234569765459999997
9987632345678989436799699965488987989398998765452983278954589998767678998989877410165698864348999876
9876545656789678945678989876599435678987769876879874367895678989878789987898764321234987653237898765
9987656787894569876989876989678924569876646987998765458998789876989899876789985542349876740126897654
9898789898923478987899965498789013498765435598999876569549898765491958965678997643598765432234789733
7659899949012568999998654349898923987654323459789989678956999987210247893234987654679876646545678921
8943987632123499998987543235967899876543212345678998789767999976321356932123798767898989757

In [8]:
!tail $PATH

8934589765639876567656789434567988698756567897569898767896569876789898934987898543236789651234976563
9125678954323997879878992123458999796645456789678999658789498765678999129876789654345898743999895432
1014567896212598998989943254569234985432346899989889545678987654589991019965699976456789859886789421
2123698965403459987899854365678959874321234589998775434569898767678989198764789897567898998765678942
5436789876514998896789765498789198765210123478999654323459799878989678987653456789678967987954567893
6545678984329876745678996568893239654341234567896543212997689989294569876532345678999659876543478954
7676789996534965434556789678965498765454345678987654329876589990123456987646756789876545989832349895
8987996987649876323645678989876989876565656789498765435987678921247897898767897896543234598747456797
9598945699799765101234678994989878987676987892349989745698799432356998959988998965432123459656567898
3459656789987654212345789543298769998987898921235697656789896565467899543299439878943434598

In [9]:
# other input
l = []
with open(PATH, 'r') as f:
    for i in f:
        l.append(i.strip())
len(l)

100

In [11]:
len(l[0])

100

In [13]:
arr = np.zeros((100,100))
for i,x in enumerate(l):
    arr[i,:] = np.array(list(map(int, x)))
print(arr.shape)

(100, 100)


In [19]:
test_st = """2199943210
3987894921
9856789892
8767896789
9899965678"""
test_arr = np.array([list(map(int, l)) for l in test_st.split('\n')])
print(test_arr)
print(test_arr.shape)

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
(5, 10)


In [14]:
padded_arr = np.ones((102, 102)) * 9
padded_arr[1:-1, 1:-1] = arr
print(padded_arr)

[[9. 9. 9. ... 9. 9. 9.]
 [9. 8. 7. ... 3. 4. 9.]
 [9. 9. 8. ... 4. 9. 9.]
 ...
 [9. 9. 5. ... 9. 8. 9.]
 [9. 3. 4. ... 9. 9. 9.]
 [9. 9. 9. ... 9. 9. 9.]]


In [ ]:
padded_arr[:-1, :-1] < padded_arr[]

In [59]:
def solve1(a):
    n, m = a.shape
    padded_a = np.ones((n+2, m+2)) * 9
    padded_a[1:-1, 1:-1] = a
#     print(padded_a[1:-1,1:-1])
    dips = (padded_a[1:-1,1:-1] < padded_a[:-2,1:-1]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[1:-1,2:]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[1:-1,:-2]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[2:,1:-1]).astype(int)
    print(padded_a[1:-1,1:-1].astype(int))
    print(dips)
    return int(np.sum(dips * (padded_a[1:-1,1:-1] + 1)))

def explore(a, x, y, explored):
    n, m = a.shape
    if x >= 1 and a[x-1, y] > a[x, y] and explored[x-1, y] == 0 and a[x-1, y] != 9:
        explored[x-1, y] = 1
        explored = explore(a, x-1, y, explored)
    if y >= 1 and a[x, y-1] > a[x, y] and explored[x, y-1] == 0 and a[x, y-1] != 9:
        explored[x, y-1] = 1
        explored = explore(a, x, y-1, explored)
    if x < n-1 and a[x+1, y] > a[x, y] and explored[x+1, y] == 0 and a[x+1, y] != 9:
        explored[x+1, y] = 1
        explored = explore(a, x+1, y, explored)
    if y < m-1 and a[x, y+1] > a[x, y] and explored[x, y+1] == 0 and a[x, y+1] != 9:
        explored[x, y+1] = 1
        explored = explore(a, x, y+1, explored)
    return explored

def find_basin_size(a, x, y):
    explored = np.zeros(a.shape)
    explored[x, y] = 1
    return np.sum(explore(a, x, y, explored))

def solve2(a):
    n, m = a.shape
    padded_a = np.ones((n+2, m+2)) * 9
    padded_a[1:-1, 1:-1] = a
    dips = (padded_a[1:-1,1:-1] < padded_a[:-2,1:-1]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[1:-1,2:]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[1:-1,:-2]).astype(int)
    dips *= (padded_a[1:-1,1:-1] < padded_a[2:,1:-1]).astype(int)
    basin_sizes = []
    dip_x, dip_y = np.where(dips)
    for x, y in zip(dip_x, dip_y):
        basin_sizes.append(find_basin_size(a, x, y))
    sorted_sizes = sorted(basin_sizes)
    return int(sorted_sizes[-1] * sorted_sizes[-2] * sorted_sizes[-3])

In [52]:
solve1(test_arr)

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
[[0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]


15

In [56]:
explore(test_arr, 0, 9, np.zeros((5, 10)))

array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
solve2(test_arr)

1134

In [40]:
solve1(arr)

458

In [61]:
solve2(arr)

1391940